### ISSUE TITLE
Provide button to randomise nodes

### ISSUE THREAD

**Issue by jidel** [acjim/AcmacsDesktop#260]
Yes, no, maybe?

**Comment by rohankoid** [comment]
@acjim/member

**Comment by rohankoid** [comment]
Ok since no one spoke, I say no to this.

**Comment by jidel** [comment]
Would that be a backend functionality? If its only a new call, we could ask Eugene to provide this.

**Comment by idrissou** [comment]
What do you mean by randomize nodes? just change their positions, while keeping stress intact.
If so, then it wouldn't make much sense as a change in a node's position will affect the stress value anyways.

**Comment by rohankoid** [comment]
@idrissou no this is something professor Moore mentioned, he wanted a functionality that would simply randomize the points. 

@jidel No this is infact an easy one he just wanted a randomiser, simply loop through the array and change their position and after the change, he wanted to press repotimize manually and see if that gives completely different map (better in anyway)

Rethinking of it may be we could add it. Just have to make sure that after this, we should set pointsMoved as true.

**Comment by idrissou** [comment]
@rohankoid: I was more looking for what you wrote to jidel (y)

**Comment by idrissou** [comment]
@jidel : I will start working on this in the meantime Rohan is preparing for his exam.

**Comment by idrissou** [comment]
Done and dusted

**Comment by rohankoid** [comment]
Cool, :+1: thanks

Minor enhancements and bug:

1. tool-tip says, RanDomize
2. pointsMoved should be set as true [mandatory]
3. and setMapIsChanged(true) [optional perhaps]

**Comment by idrissou** [comment]
@rohankoid: pushed and changed the pointsMoved before you wrote the comment :) LOL

**Comment by rohankoid** [comment]
Cool, but i think something is still not right, cause the point was to randomise and when someone presses optimize button,
1. new projection 
2. relax 
should have been called. But perhaps setting the pointsMoved has some issue because right now only 
1. relax is being called which always will output same result as long as a new projection is not fed to it.


----

also the tool-tip is still labeled wrong :dango:

**Comment by idrissou** [comment]
@rohan: feel free to label it as you wish.
On anther note, reoptimize seems to not work anymore as expected
always giving the same results, even when changing the nodes

**Comment by idrissou** [comment]
I think the bug is not in this functionality as you stated. The reoptimize seems to be screwed up after the last core bundle update. giving the same results much of the time.

**Comment by rohankoid** [comment]
@idrissou I think you are taking this way too harsh. You have a typo there and that is something users can see. I am pointing it out. That's not a point to be pissed off at mate.

**Comment by idrissou** [comment]
I am not pissed off at all :) I thought you wanted to call the label something else. That's why I said feel free to call it as you want. I am all but pissed off. I'll take it just as stress exam from your side or something^^

**Comment by rohankoid** [comment]
No worries :) probably I am a little stressed and can't focus on what I need to study so I am coming here way too often hehe. 

Anyway,
Yes I noticed the same bug on re-optimisation @idrissou as you mentioned I'll open new issue for that. 

But, the one I am mentioning is a different one. It doesn't work as expected (on our side too)

To test: add `console.log('anything");` in file api.js line no. 635
1. randomize and reoptimize (console won't have anything)
2. move a point and reooptimize (console will have message from above)

**Comment by idrissou** [comment]
No worries mate. I'll investigate that

**Comment by rohankoid** [comment]
@idrissou 
using 
`scope.pointsMoved = true`
instead of 
`$rootScope.pointsMoved = true`
in [mapDirective.js#L905](https://github.com/acjim/AcmacsDesktop/blob/d353d83b111710aa1afeef365e3a0a4c0615bdb9/src/app/components/map/mapDirective.js#L905)

might save you some time

**Comment by idrissou** [comment]
Thanks mate (y).

**Comment by jidel** [comment]
The randomise function is way to non-random.. :stuck_out_tongue: 
Maybe we should look at the implementation in LispMDS or acmacs.

**Comment by rohankoid** [comment]
@jidel nah I think it should be fine, it's not for any encryption or something. Well i did modify it to be a little more random but whole point is just to scramble it to see how optimization goes with new co-ordinates.

**Comment by jidel** [comment]
Okay, I didn't mean the randomness, more the fact that all nodes seem to converge into the same direction and not all nodes are moving, some seem to stay at their position

**Comment by rohankoid** [comment]
@jidel yeah I wonder why some points don't move, every point are modified though. 
It should be much better now though.
